services:
  slskd:
    image: slskd/slskd:latest
    container_name: slskd
    
    environment:
      - SLSKD_REMOTE_CONFIGURATION=true
      - SLSKD_HTTP_PORT=5030
      - SLSKD_IP_ADDRESS=0.0.0.0  # Forces IPv4 only to stop the bind conflict
    ports:
      - "5030:5030"
      - "50300:50300"
    volumes:
      - ./data:/app  # Using a local folder is easier to debug than a volume
      - /mnt/Files/Music:/music
    restart: unless-stopped
