services:
  navidrome:
    image: deluan/navidrome:latest
    container_name: navidrome
    user: 1000:1000 # Matches your fstab uid/gid for pure performance
    ports:
      - "4533:4533"
    restart: unless-stopped
    environment:
      # Optional: Adjust scan schedule (e.g., scan every 1 hour)
      ND_SCANSCHEDULE: 1h
      ND_LOGLEVEL: info  
      ND_SESSIONTIMEOUT: 24h
      ND_BASEURL: ""
      ND_IMAGECACHESIZE: "500MB"
    volumes:
      - "./data:/data"
      - "/mnt/Files/Music:/music:ro" # Maps your music folder as Read-Only
